baseurl: "https://weitao.netlify.app/"
languageCode: "en-us"
title: "Weitao Chen | 陈伟涛"
theme: "hugo-ivy"
disqusShortname: "yihui"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "English"
      url: "/en/"
      weight: 1
    - name: "中文"
      url: "/cn/"
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "中文"
      url: "/cn/"
      weight: 3
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/post/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "事务"
      url: "/cn/todo/"
      weight: 4
    - name: "English"
      url: "/en/"
      weight: 5
params:
  description: "Personal website of Weitao Chen; 陈伟涛的个人网站"
  footer: "&copy; [Weitao Chen](/) 2001 - 2021"
  disqusURL: "https://weitao.netlify.app"
  disqusShortname: "weitao-chen" #看disqus教程，不用改disqus.html
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/Chen-Weitao/weitao/edit/main/content/"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Weitao Chen"
      tag: ""

  author:
    en: "Weitao Chen | 陈伟涛"
    cn: "Weitao Chen | 陈伟涛"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  goldmark:
    renderer:
      unsafe: true
